version: "3.9"

services:

  springboot-mongo:
    container_name: springboot-mongo
    build: .
    image: springboot-mongo
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo
    ports:
      - 27017:27017
    image: mongo:7.0
    volumes:
      - ./mongo_data:/data/db
    restart: always